import type { Review, Race } from "./types";

export const mockReviews: Review[] = [
  {
    author: "Jane Doe",
    avatarUrl: "https://picsum.photos/200/200?random=1",
    rating: 4,
    text: "The race was thrilling from start to finish! The atmosphere at the Red Bull Ring is always electric. Great organization.",
    date: "2025-07-01",
  },
  {
    author: "John Smith",
    avatarUrl: "https://picsum.photos/200/200?random=2",
    rating: 5,
    text: "An absolute masterpiece of a Grand Prix. We saw some incredible overtakes and a surprise winner. Can't wait for next year!",
    date: "2025-07-02",
  },
  {
    author: "Alice Johnson",
    avatarUrl: "https://picsum.photos/200/200?random=3",
    rating: 3,
    text: "It was a decent race, but the traffic getting to the circuit was a nightmare. The on-track action was good, but logistics could be improved.",
    date: "2025-07-02",
  },
  {
    author: "Michael Rodriguez",
    avatarUrl: "https://picsum.photos/200/200?random=4",
    rating: 5,
    text: "Absolutely incredible! The wheel-to-wheel racing was phenomenal. Best Grand Prix I've attended in years. The facilities were top-notch.",
    date: "2025-07-03",
  },
  {
    author: "Sarah Chen",
    avatarUrl: "https://picsum.photos/200/200?random=5",
    rating: 2,
    text: "Disappointed with the race. Too much strategy play and not enough on-track action. The weather didn't help either. Expected more excitement.",
    date: "2025-07-04",
  },
  {
    author: "David Thompson",
    avatarUrl: "https://picsum.photos/200/200?random=6",
    rating: 4,
    text: "Great race with some fantastic overtakes! The crowd was amazing and the circuit atmosphere was electric. Food options could be better though.",
    date: "2025-07-05",
  },
  {
    author: "Emily Foster",
    avatarUrl: "https://picsum.photos/200/200?random=7",
    rating: 5,
    text: "What a spectacular weekend! The qualifying session was nail-biting and the race delivered on all fronts. Will definitely be back next year!",
    date: "2025-07-06",
  },
  {
    author: "Robert Martinez",
    avatarUrl: "https://picsum.photos/200/200?random=8",
    rating: 3,
    text: "Solid race overall. The track action was good but not exceptional. Parking was a mess and took forever to get out. Mixed feelings about the experience.",
    date: "2025-07-07",
  },
  {
    author: "Lisa Park",
    avatarUrl: "https://picsum.photos/200/200?random=9",
    rating: 4,
    text: "Loved the race! The new regulations really made for closer racing. The pit stop strategies were fascinating to watch. Great weekend overall.",
    date: "2025-07-08",
  },
  {
    author: "James Wilson",
    avatarUrl: "https://picsum.photos/200/200?random=10",
    rating: 1,
    text: "Terrible experience. Rain delayed everything, couldn't see much from our seats, and the merchandise was overpriced. Very disappointing weekend.",
    date: "2025-07-09",
  },
  {
    author: "Anna Kowalski",
    avatarUrl: "https://picsum.photos/200/200?random=11",
    rating: 5,
    text: "Outstanding Grand Prix! The racing was intense and unpredictable. Perfect weather, great crowd, and excellent commentary. Exceeded all expectations!",
    date: "2025-07-10",
  },
  {
    author: "Chris Taylor",
    avatarUrl: "https://picsum.photos/200/200?random=12",
    rating: 4,
    text: "Really enjoyed the race weekend. The support races were entertaining too. Some organizational hiccups but the main event was worth it. Good value for money.",
    date: "2025-07-11",
  },
  {
    author: "Maria Santos",
    avatarUrl: "https://picsum.photos/200/200?random=13",
    rating: 3,
    text: "Average race with a few exciting moments. The facilities were clean and well-maintained. Wish there was more action in the final third of the race.",
    date: "2025-07-12",
  },
];

export const races2025: Race[] = [
  { id: "austrian-grand-prix-2025", name: "Austrian GP", latestRace: true },
  { id: "british-grand-prix-2025", name: "British GP" },
  { id: "belgian-grand-prix-2025", name: "Belgian GP" },
  { id: "hungarian-grand-prix-2025", name: "Hungarian GP" },
  { id: "dutch-grand-prix-2025", name: "Dutch GP" },
  { id: "italian-grand-prix-2025", name: "Italian GP" },
  { id: "azerbaijan-grand-prix-2025", name: "Azerbaijan GP" },
  { id: "singapore-grand-prix-2025", name: "Singapore GP" },
  { id: "united-states-grand-prix-2025", name: "United States GP" },
  { id: "mexico-city-grand-prix-2025", name: "Mexico City GP" },
  { id: "são-paulo-grand-prix-2025", name: "São Paulo GP" },
  { id: "las-vegas-grand-prix-2025", name: "Las Vegas GP" },
  { id: "qatar-grand-prix-2025", name: "Qatar GP" },
  { id: "abu-dhabi-grand-prix-2025", name: "Abu Dhabi GP" },
  { id: "australian-grand-prix-2025", name: "Australian GP" },
  { id: "chinese-grand-prix-2025", name: "Chinese GP" },
  { id: "japanese-grand-prix-2025", name: "Japanese GP" },
  { id: "bahrain-grand-prix-2025", name: "Bahrain GP" },
  { id: "saudi-arabian-grand-prix-2025", name: "Saudi Arabian GP" },
  { id: "miami-grand-prix-2025", name: "Miami GP" },
  { id: "emilia-romagna-grand-prix-2025", name: "Emilia Romagna GP" },
  { id: "monaco-grand-prix-2025", name: "Monaco GP" },
  { id: "spanish-grand-prix-2025", name: "Spanish GP" },
  { id: "canadian-grand-prix-2025", name: "Canadian GP" },
];

export const grandPrixes: Race[] = [...races2025];
